services:
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: recipe
      POSTGRES_DB: recipe_finder
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && rails db:migrate && rails server -b 0.0.0.0"
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:recipe@db:5432/recipe_finder
      ALLOWED_ORIGINS: http://localhost:5173,http://localhost:5173/,http://localhost:5175,http://localhost:5175/

  migrate:
    build: .
    command: bash -c "rails db:create db:migrate"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:recipe@db:5432/recipe_finder

  test:
    build: .
    command: bash -c "RAILS_ENV=test rails db:create db:migrate && RAILS_ENV=test bundle exec rspec"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgres://postgres:recipe@db:5432/recipe_finder_test

volumes:
  postgres_data:

